version: '3'

services:
  web:
    build: .
    container_name: node
    command: npm start
    environment:
      NODE_ENV: development
    volumes:
      - ./src:/code
      - /code/node_modules
    ports:
      - 3000:3000
    depends_on:
      - db

  db:
    image: mongo:4.0.10
    container_name: mongodb
    volumes:
      - jsCRiSP_data:/data/db

volumes:
  jsCRiSP_data:
